# -*- coding:utf-8 -*-

"""Game of brain-even."""

import random

from brain_games import engine

QUESTION = 'Answer "yes" if number even otherwise answer "no".'
RANDOM_FROM = 1
RANDOM_TO = 25


def is_even(number) -> bool:
    """
    Check, if number is even or not.

    Args:
        number: was generated by call_random function.

    Returns:
        bool: True is even, False is odd.
    """
    return not number % 2


def convert_bool_to_str(answer) -> str:
    """
    Convert True into 'yes', False into 'no'.

    Args:
        answer: bool.

    Returns:
        str: 'yes' or 'no'.
    """
    if answer is True:
        return 'yes'
    return 'no'


def get_question_and_answer() -> (str, str):
    """
    Get answer from user and calculate correct answer.

    Returns:
        str: question for user.
        str: correct answer.
    """
    number = random.randint(RANDOM_FROM, RANDOM_TO)     # noqa: S311
    correct = is_even(number)
    answer = convert_bool_to_str(correct)
    question = ' '.join(['Question:', str(number)])
    return question, answer


def start_game():
    """Make game logic."""
    engine.play_game(QUESTION, get_question_and_answer)
